### ISSUE TITLE
It'd be nice to make -mapping-config optional

### ISSUE THREAD

**Issue by bryanlarsen** [messagebird/beanstalkd_exporter#23]
It'd be nice to make -mapping-config optional, or at least tell people that -mapping-config=/dev/null works.

**Comment by bryanlarsen** [comment]
-mapping-config=/dev/null doesn't work with latest version of the exporter.

**Comment by bryanlarsen** [comment]
OK, now I'm confused.

```
docker run -it --rm croudtech/prometheus-beanstalk-exporter -beanstalkd.address serv093.vpn.threehub.net:11300 -mapping-config=/dev/null
2018/08/01 18:57:44 main.go:216: Listening on port :8080 .
2018/08/01 18:57:44 main.go:217: Polling serv093.vpn.threehub.net:11300 for stats every 30 seconds
```

```
docker run -it --rm bryanlarsen/beanstalkd_exporter -beanstalkd.address serv093.vpn.threehub.net:11300 -mapping-config /etc/beanstalkd_exporter/mapping.conf
panic: inconsistent label cardinality

goroutine 9 [running]:
github.com/messagebird/beanstalkd_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*MetricVec).With(0xc4201da2c0, 0xc4201de660, 0x2, 0xc4201e4320)
	/go/src/github.com/messagebird/beanstalkd_exporter/vendor/github.com/prometheus/client_golang/prometheus/vec.go:146 +0x76
github.com/messagebird/beanstalkd_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*GaugeVec).With(0xc4201e6050, 0xc4201de660, 0x0, 0x0)
	/go/src/github.com/messagebird/beanstalkd_exporter/vendor/github.com/prometheus/client_golang/prometheus/gauge.go:115 +0x38
main.(*Exporter).statTube(0xc420168bd0, 0xc420010e60, 0xc4201e0160, 0x7, 0xc420071f88)
	/go/src/github.com/messagebird/beanstalkd_exporter/exporter.go:230 +0x6c7
main.(*Exporter).scrape(0xc420168bd0, 0xc420071f88)
	/go/src/github.com/messagebird/beanstalkd_exporter/exporter.go:173 +0x682
main.(*Exporter).Describe(0xc420168bd0, 0xc420012cc0)
	/go/src/github.com/messagebird/beanstalkd_exporter/exporter.go:86 +0x89
github.com/messagebird/beanstalkd_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Register.func1(0xa7cb80, 0xc420168bd0, 0xc420012cc0)
	/go/src/github.com/messagebird/beanstalkd_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:292 +0x3b
created by github.com/messagebird/beanstalkd_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Register
	/go/src/github.com/messagebird/beanstalkd_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:291 +0x113
```

I have no idea what version croudtech/prometheus-beanstalk-exporter is, which is why I'm trying to use my own build, which is https://github.com/messagebird/beanstalkd_exporter/pull/25

**Comment by marcelcorso** [comment]
the default value for the flag is the empty string "". A bit lower on the main function we check if it's == "" then we don't do any mapping. 

https://github.com/messagebird/beanstalkd_exporter/blob/7248ae302d7db8703bc81a9bca26f791897fffbd/main.go#L69

so this shouldn't be a problem.
